# Site settings
title: Couture that Rox
email: info@couturethatrox.com

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/couturerox"
url: "http://kaymic.com/couturerox"
storeurl: "http://couturethatrox.storenvy.com"

banner_url: /images/header2.png

twitter_username: couturethatrox

paginate: 10
# paginate_path: "portfolio/:num"

# Build settings
markdown: kramdown
permalink: pretty

exclude: [storenvy]

gems:
 - jekyll-coffeescript
 - jekyll-paginate
